home:
    pattern:  /
    defaults: { _controller: CoderdojoWebsiteBundle:Default:index }

about:
    pattern:  /over-coderdojo
    defaults: { _controller: CoderdojoWebsiteBundle:Default:about }

dojo:
    pattern:  /dojos/{city}
    defaults: { _controller: CoderdojoWebsiteBundle:Default:dojo }

dojos:
    pattern:  /dojos
    defaults: { _controller: CoderdojoWebsiteBundle:Default:dojos }

stichting:
    pattern:  /over-de-stichting
    defaults: { _controller: CoderdojoWebsiteBundle:Default:stichting }

setup:
    pattern:  /opstarten
    defaults: { _controller: CoderdojoWebsiteBundle:Default:setup }

material:
    pattern:  /materiaal
    defaults: { _controller: CoderdojoWebsiteBundle:Default:material }

contact:
    pattern:  /contact
    defaults: { _controller: CoderdojoWebsiteBundle:Default:contact }

old-manage:
    path: /beheren
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: manage
        permanent: true

manage:
    pattern:  /mijn-dojo/beheren
    defaults: { _controller: CoderdojoWebsiteBundle:Default:manage }

new-dojo:
    pattern:  /mijn-dojo/beheren/toevoegen
    defaults: { _controller: CoderdojoWebsiteBundle:Default:manageAdd }

list-dojos:
    pattern: /api/dojos
    defaults: { _controller: CoderdojoWebsiteBundle:Default:listDojos }