parameters:
#    coderdojo_website.example.class: CoderDojo\WebsiteBundle\Example

services:
    coder_dojo.form.registration:
        class: CoderDojo\WebsiteBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    coder_dojo.form.profile:
        class: CoderDojo\WebsiteBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: coderdojo_user_profile }

    coder_dojo.form.contact:
        class: CoderDojo\WebsiteBundle\Form\Type\ContactFormType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: coderdojo_contact_form }

    coder_dojo.form.event:
        class: CoderDojo\WebsiteBundle\Form\Type\EventFormType
        tags:
            - { name: form.type, alias: coderdojo_event }

    coder_dojo.website_bundle.slack_service:
        class: CoderDojo\WebsiteBundle\Service\SlackService
        arguments: ["%slack_api_token%", "@kernel"]

    coder_dojo.website_bundle.handler.create_dojo_handler:
        class: CoderDojo\WebsiteBundle\Handler\CreateDojoHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\CreateDojoCommand"}

    coder_dojo.website_bundle.handler.remove_dojo_handler:
        class: CoderDojo\WebsiteBundle\Handler\RemoveDojoHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\RemoveDojoCommand"}

    coder_dojo.website_bundle.subscriber.dojo_created_event.notify_slack:
        class: CoderDojo\WebsiteBundle\Subscriber\DojoCreatedEvent\NotifySlack
        arguments: ["@coder_dojo.website_bundle.slack_service"]
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\DojoCreatedEvent"}