parameters:
#    coderdojo_website.example.class: CoderDojo\WebsiteBundle\Example

services:
    coder_dojo.form.registration:
        class: CoderDojo\WebsiteBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    coder_dojo.form.profile:
        class: CoderDojo\WebsiteBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: coderdojo_user_profile }

    coder_dojo.form.accept_privacy:
        class: CoderDojo\WebsiteBundle\Form\Type\PrivacyFormType
        tags:
            - { name: form.type, alias: coderdojo_privacy_form }

    coder_dojo.form.contact:
        class: CoderDojo\WebsiteBundle\Form\Type\ContactFormType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: coderdojo_contact_form }

    coder_dojo.form.coc_request:
        class: CoderDojo\WebsiteBundle\Form\Type\CocRequestFormType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type, alias: coderdojo_coc_request_form }

    coder_dojo.form.event:
        class: CoderDojo\WebsiteBundle\Form\Type\EventFormType
        tags:
            - { name: form.type, alias: coderdojo_event }

    coder_dojo.twig_extension.random:
        class: CoderDojo\WebsiteBundle\Twig\RandomExtension
        public: false
        tags:
            - { name: twig.extension }

    coder_dojo.twig_extension.dojo:
        class: CoderDojo\WebsiteBundle\Twig\DojoExtension
        public: false
        tags:
            - { name: twig.extension }

    coder_dojo.website_bundle.repository.dojo:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - CoderDojo\WebsiteBundle\Entity\Dojo

    coder_dojo.website_bundle.slack_service:
        class: CoderDojo\WebsiteBundle\Service\SlackService
        arguments: ["%slack_api_token%", "@kernel"]

    coder_dojo.website_bundle.handler.create_coc_request_handler:
        class: CoderDojo\WebsiteBundle\Handler\CreateCocRequestHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\CreateCocRequestCommand"}

    coder_dojo.website_bundle.handler.create_dojo_handler:
        class: CoderDojo\WebsiteBundle\Handler\CreateDojoHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\CreateDojoCommand"}

    coder_dojo.website_bundle.handler.remove_dojo_handler:
        class: CoderDojo\WebsiteBundle\Handler\RemoveDojoHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\RemoveDojoCommand"}

    coder_dojo.website_bundle.handler.remove_event_handler:
        class: CoderDojo\WebsiteBundle\Handler\RemoveEventHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\RemoveEventCommand"}

    coder_dojo.website_bundle.handler.create_event_handler:
        class: CoderDojo\WebsiteBundle\Handler\CreateEventHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\CreateEventCommand"}

    coder_dojo.website_bundle.handler.prepare_coc_request_handler:
        class: CoderDojo\WebsiteBundle\Handler\PrepareCocRequestHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\PrepareCocRequestCommand"}

    coder_dojo.website_bundle.handler.expire_coc_request_handler:
        class: CoderDojo\WebsiteBundle\Handler\ExpireCocRequestHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\ExpireCocRequestCommand"}

    coder_dojo.website_bundle.handler.ship_coc_request_handler:
        class: CoderDojo\WebsiteBundle\Handler\ShipCocRequestHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\ShipCocRequestCommand"}

    coder_dojo.website_bundle.handler.receive_coc_request_handler:
        class: CoderDojo\WebsiteBundle\Handler\ReceiveCocRequestHandler
        arguments: ["@event_recorder", "@doctrine"]
        tags:
          - { name: command_handler, handles: "CoderDojo\\WebsiteBundle\\Command\\ReceiveCocRequestCommand"}

    coder_dojo.website_bundle.subscriber.dojo_created_event.notify_slack:
        class: CoderDojo\WebsiteBundle\Subscriber\DojoCreatedEvent\NotifySlack
        arguments: ["@coder_dojo.website_bundle.slack_service"]
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\DojoCreatedEvent"}

    coder_dojo.website_bundle.subscriber.event_created_event.notify_slack:
        class: CoderDojo\WebsiteBundle\Subscriber\EventCreatedEvent\NotifySlack
        arguments:
          - "@coder_dojo.website_bundle.slack_service"
          - "@coder_dojo.website_bundle.repository.dojo"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\EventCreatedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_created_event.notify_champion:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestCreatedEvent\NotifyChampion
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestCreatedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_created_event.notify_foundation:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestCreatedEvent\NotifyFoundation
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestCreatedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_created_event.notify_volunteer:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestCreatedEvent\NotifyVolunteer
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestCreatedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_prepared_event.notify_volunteer:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestPreparedEvent\NotifyVolunteer
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestPreparedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_prepared_event.notify_champion:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestPreparedEvent\NotifyChampion
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestPreparedEvent"}

#    coder_dojo.website_bundle.subscriber.coc_request_shipped_event.notify_foundation:
#        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestShippedEvent\NotifyFoundation
#        arguments:
#            - "@mailer"
#            - "@templating"
#            - "@doctrine"
#        tags:
#            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestShippedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_received_event.notify_champion:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestReceivedEvent\NotifyChampion
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestReceivedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_received_event.notify_volunteer:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestReceivedEvent\NotifyVolunteer
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestReceivedEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_expired_event.notify_champion:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestExpiredEvent\NotifyChampion
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestExpiredEvent"}

    coder_dojo.website_bundle.subscriber.coc_request_expired_event.notify_volunteer:
        class: CoderDojo\WebsiteBundle\Subscriber\CocRequestExpiredEvent\NotifyVolunteer
        arguments:
            - "@mailer"
            - "@templating"
            - "@doctrine"
        tags:
            - { name: event_subscriber, subscribes_to: "CoderDojo\\WebsiteBundle\\Event\\CocRequestExpiredEvent"}

    coder_dojo.website_bundle.ecurring:
        public: true
        class: CoderDojo\WebsiteBundle\Service\Ecurring
        arguments:
            - '@eight_points_guzzle.client.ecurring'
            - '@router'
            - '%ecurring_quartely_plan_id%'
            - '%ecurring_semi_yearly_plan_id%'
            - '%ecurring_yearly_plan_id%'
            - '%ecurring_yearly_after_may_plan_id%'

