parameters:
#    coderdojo_website.example.class: Coderdojo\WebsiteBundle\Example

services:
    coderdojo.form.registration:
        class: Coderdojo\WebsiteBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    coderdojo.form.profile:
        class: Coderdojo\WebsiteBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: coderdojo_user_profile }

    coderdojo.form.contact:
        class: Coderdojo\WebsiteBundle\Form\Type\ContactFormType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: coderdojo_contact_form }

    coderdojo.website_bundle.slack_service:
        class: Coderdojo\WebsiteBundle\Service\SlackService
        arguments: ["%slack_api_token%", "@kernel"]
