language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6@stable
  - cp app/config/parameters.yml.test.dist app/config/parameters.yml

install: composer install --prefer-dist --no-interaction

script:
  - phpunit -c app/ --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/coveralls -v; fi;'
