language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction

script:
  - phpunit -c app/ --coverage-text