language: php

php:
  - 5.6
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'create database coderdojonl;'
  - cp app/config/parameters.yml.test.dist app/config/parameters.yml
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6@stable

install: composer install --prefer-dist --no-interaction

script:
  - phpunit -c --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/coveralls -v; fi;'
