language: php

php:
  - 5.6

sudo: false

addons:
  code_climate:
    repo_token: c0ea634b3fd562679652608188fc52b9888471af125334ad1b8e7d6ca22761bd

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction

script:
  - phpunit -c app/ --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter