language: php
# trigger build
php:
  - 7.1

branches:
  only: 
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
#  - mysql -e 'create database coderdojonl;'
#  - cp app/config/parameters.yml.test.dist app/config/parameters.yml
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6@stable

install: composer install --prefer-dist --no-interaction --no-scripts

script:
  - bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/coveralls -v; fi;'
  - echo $DEPLOY_KEY >> ~/.ssh/coderdojo_deploy
  - gem install net-ssh -v '4.1.0'
  - bundle install
  - bundle exec cap production deploy
