version: "3.1"
services:

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_DATABASE=coderdojo
        - MYSQL_USER=coderdojo
        - MYSQL_PASSWORD=1234
      ports:
        - "8082:3306"

    nginx:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    fpm:
      build: docker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    cli:
      build: docker/php-cli
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-cli/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
