version: "3.1"
services:

  mysql:
    image: mysql:5.7
    working_dir: /application
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=coderdojo
      - MYSQL_USER=coderdojo
      - MYSQL_PASSWORD=1234
    ports:
      - "8082:3306"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
        - .:/application:cached
        - cache:/application/var/cache
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    networks:
      - backend
      - frontend

  fpm:
    build: docker/php-fpm
    working_dir: /application
    volumes:
      - .:/application:cached
      - cache:/application/var/cache
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - backend

  cli:
    build: docker/php-cli
    working_dir: /application
    volumes:
      - .:/application:cached
      - cache:/application/var/cache
      - ./docker/php-cli/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
    networks:
      - backend

volumes:
  mysql-data:
  cache:
  composer:

networks:
  frontend:
  backend:
