fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

old-manage:
    path: /beheren
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: manage
        permanent: true

coderdojo_website:
    resource: "@CoderdojoWebsiteBundle/Controller/"
    prefix:   /
    type:     annotation