fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

old-manage:
    path: /beheren
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: manage
        permanent: true

old-setup:
    path: /opstarten
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: setup
        permanent: true

old-material:
    path: /materiaal
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: material
        permanent: true

old-about:
    path: /over-coderdojo
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about
        permanent: true

old-foundation:
    path: /over-de-stichting
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: foundation
        permanent: true

old-collaboration:
    path: /samenwerkingen
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true

codeqube-alias:
    path: /codeqube
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: codeqube
        permanent: true

codeweek-alias:
    path: /samenwerkingen/eu-code-week
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: codeweek
        permanent: true

old-html:
    path: /html-1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: online_course_html_css_1
        permanent: true

vog-alias:
    path: /vog
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /nieuws/dojo-support/vraag-een-gratis-vog-aan-voor-vrijwilligers
        permanent: true

corona:
    path: /corona
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /nieuws/dojo-support/coderdojo-in-tijden-van-corona
        permanent: true

hack-challenge:
    path: /hack-challenge
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /nieuws/events/hack-challenges-competitie
        permanent: false

coder_dojo_website:
    resource: "@CoderDojoWebsiteBundle/Controller"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
